const x0 = 20;
const y0 = 30;
const r = 10;
const interLetterSpace = r;
let x = interLetterSpace + r;
letter_I(x, y0, r);
x += interLetterSpace + 2 * r * width_I;
letter_H(x, y0, r);
x += interLetterSpace + 2 * r * width_H;
letter_H(x, y0, r);